name: rest-countries

services:
  rest-countries-dev:
    build: .
    image: rest-countries:1.0
    container_name: rest-countries
    command: pnpm dev
    ports:
      - 3001:3001
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - package.json
        - action: rebuild
          path: package.json