export const FETCH_COUNTRIES_REQUEST: string = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS: string = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FEILURE: string = 'FETCH_COUNTRIES_FEILURE';